export const FETCH_BOAT_RAMPS_DATA = "FETCH_BOAT_RAMPS_DATA";
export const FETCH_BOAT_RAMPS_DATA_FAILURE = "FETCH_BOAT_RAMPS_DATA_FAILURE";
export const SET_BOAT_RAMPS_MAP_VIEWPORT = "SET_BOAT_RAMPS_MAP_VIEWPORT";
export const SET_BOAT_RAMPS_MAP_FEATURES_FILTER = "SET_BOAT_RAMPS_MAP_FEATURES_FILTER";
export const SET_BOAT_RAMPS_MAP_FILTER = "SET_BOAT_RAMPS_MAP_FILTER";
export const SET_BOAT_RAMPS_MAP_CHARTS_COLORS = "SET_BOAT_RAMPS_MAP_CHARTS_COLORS";